server:
  port: 9080

api:
  zomato:
    uri-establishments: https://developers.zomato.com/api/v2.1/establishments
    api-key-name: user-key
    api-key-value: 1253ecfe4cce84f6723ef97c2780e4b3
  database:
    files-location: database
    key-cipher: 1r8+24pibarAWgS85/Heeg==
  jwt:
    id: tybaChallengeJWT
    secret-key: tybaSecretKeyJWT
    expiration-millis: 600000
  messages:
    login:
      'user-does-not-exist': 'User does not exist.'
      'invalid-credentials': 'Invalid credentials.'
      default: 'Nuestros sistemas est치n fallando. Te invitamos a intentarlo m치s tarde.'
    restaurants:
      'search-parameters-are-invalid': 'Search parameters are invalid.'
      default: 'Nuestros sistemas est치n fallando. Te invitamos a intentarlo m치s tarde.'




